version: '3.8'

services:
  z80-cpu:
    build:
      context: ./
      dockerfile: Dockerfile.cpu
    container_name: z80-cpu
    tty: true
    stdin_open: true
    environment:
      DISPLAY: "host.docker.internal:0"
    volumes:
      - ./tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./csharp:/projects/csharp
      - ./cpp:/projects/cpp
      - ./:/projects/docker
      - ./profiles/vscode:/root/.config/Code
      - ./profiles/chrome:/root/.config/google-chrome
    working_dir: /projects

  z80-gpu:
    build:
      context: ./
      dockerfile: Dockerfile.gpu
    container_name: z80-gpu
    runtime: nvidia
    tty: true
    stdin_open: true
    environment:
      DISPLAY: "host.docker.internal:0"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - ./tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./csharp:/projects/csharp
      - ./cpp:/projects/cpp
      - ./:/projects/docker
      - ./profiles/vscode:/root/.config/Code
      - ./profiles/chrome:/root/.config/google-chrome
    working_dir: /projects
